name: 🤖

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4

      - name: 🐍 Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: 'pip'

      - name: 📦 Install Black
        run: pip install black

      - name: 🎨 Format code
        run: black . --line-length 100 --exclude '/(venv|build|dist|libs)/'

      - name: 💾 Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "🤖"
          # Eliminamos las líneas de "commit_user_name" para que use el por defecto 
          # o pon tus datos reales aquí:
          commit_user_name: "alexpreciado94"